# Generated by Django 4.1.3 on 2022-12-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Blog',
        ),
    ]
